n = int(input('Введите натуральное число: '))
string = ''
counter = 0
num = 1
while counter + num <= n:
    print(str(num) * num, end='')
    counter += num
    num += 1
print(str(num) * (n - counter), end='')
