# Generated by Django 4.2.7 on 2023-11-14 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=150, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Введите текстовый идентификатор категории', max_length=200, verbose_name='Текстовый идентификатор категории')),
                ('image', models.ImageField(help_text='Вставьте изображение для категории', upload_to='', verbose_name='Иллюстрация категории')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название подкатегории', max_length=150, verbose_name='Название подкатегории')),
                ('slug', models.SlugField(help_text='Введите текстовый идентификатор подкатегории', max_length=200, verbose_name='Текстовый идентификатор подкатегории')),
                ('image', models.ImageField(help_text='Вставьте изображение для подкатегории', upload_to='', verbose_name='Иллюстрация подкатегории')),
                ('category', models.ForeignKey(help_text='Укажите категорию для подкатегории', on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='products.category', verbose_name='Категория')),
            ],
        ),
    ]
