# Generated by Django 4.2.7 on 2023-11-17 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество продукта в корзине'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_cart', to=settings.AUTH_USER_MODEL, verbose_name='Владелец корзины'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_cart', to='products.product', verbose_name='Продукт в корзине пользователя'),
        ),
    ]
